export const AUTO = 'auto';
export const INITIAL = 'initial';
export const INHERIT = 'inherit';
export const NONE = 'none';
export const HUNDRED_PERCENT = '100%';
export const ZERO_PIXELS = '0';

export const PERCENT = '%';
export const PIXELS = 'px';
export const INCHES = 'in';
export const CENTIMETERS = 'cm';
export const MILLIMETERS = 'mm';
export const PICAS = 'pc'; // 12 points or 1/6 of an inch
export const POINTS = 'pt'; // 1/72 of an inch
export const EM = 'em'; // Font-size of the current element, specifically the width of the capital "M"
export const EX = 'ex'; // Height of the lowercase "x"
export const CH = 'ch'; // Width of the character 0
export const ROOT_EM = 'rem'; // Font-size of the root element (html)
export const VIEWPORT_HEIGHT = 'vh'; // 1/100 of the viewport height
export const VIEWPORT_WIDTH = 'vw'; // 1/100 of the viewport width
export const VIEWPORT_MIN = 'vmin'; // Min of vh and vw
